GET http://localhost:3000/todos/?TO%20DO

###
GET http://localhost:3000/todos/2/
###
POST http://localhost:3000/todos/
Content-Type:application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###
PUT http://localhost:3000/todos/1/?todo="DO"
###
PUT http://localhost:3000/todos/3/?status=INPROGRESS
###

PUT http://localhost:3000/todos/2/?priority=HIGH

###
DELETE http://localhost:3000/todos/2/